In [2]:
import numpy as np

### Create Numpy Array from Python Lists

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
np.array([1,2,3,4],dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [6]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [10]:
a.shape
a.size

6

### Creating Numpy Arrays from Scratch

In [13]:
#zeros - tao mang toan so 0
np.zeros([2,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
#ones - tao mang toan so 1
np.ones([2,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [15]:
#Tao mang tu a-b
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.full((3,5),12)

array([[12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12]])

In [17]:
#Tao ra khoang cach nhau tuyen tinh
np.linspace(4,12,4)

array([ 4.        ,  6.66666667,  9.33333333, 12.        ])

In [21]:
#Seed for reproducibility
np.random.seed(0) #random ra nhieu may la nhu nhau
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [22]:
np.random.randint(1,30,[2,3])

array([[20, 17, 20],
       [ 6, 16, 16]])

### Array Indexing & Slicing

In [23]:
x1=np.random.randint(20,size=6)
x1

array([ 0, 18,  3, 17, 19, 19])

# Slicing
## x[start: stop : step]