In [2]:
import numpy as np

### Create Numpy Array from Python Lists

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
np.array([1,2,3,4],dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [6]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [10]:
a.shape
a.size

6

### Creating Numpy Arrays from Scratch

In [13]:
#zeros - tao mang toan so 0
np.zeros([2,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
#ones - tao mang toan so 1
np.ones([2,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [15]:
#Tao mang tu a-b
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.full((3,5),12)

array([[12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12]])

In [17]:
#Tao ra khoang cach nhau tuyen tinh
np.linspace(4,12,4)

array([ 4.        ,  6.66666667,  9.33333333, 12.        ])

In [21]:
#Seed for reproducibility
np.random.seed(0) #random ra nhieu may la nhu nhau
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [22]:
np.random.randint(1,30,[2,3])

array([[20, 17, 20],
       [ 6, 16, 16]])

### Array Indexing & Slicing

In [23]:
x1=np.random.randint(20,size=6)
x1

array([ 0, 18,  3, 17, 19, 19])

# Slicing
## x[start: stop : step]

# Introduction
### * Numpy ii a Python library
### * For sciencetific computations
### * Numpy arrays are multi-dimensional arrays

In [2]:
#create numpy array
# from list
import numpy as np
l=list(range(1,4))
arr=np.array(l)
print(arr)

[1 2 3]


In [5]:
#COMMON ATTRIBUTES
# dtype: data type
# shape: return a tuple of elements in dimension
# ndim: return #demesion

#Tao list 1 chieu
list1D=[1,2,3]
data=np.array(list1D)
print(data)
print(data.shape)
print(data.ndim)


[1 2 3]
(3,)
1


In [6]:
#Tao list 2 chieu
#------------------------

list2D=np.array([[1,2],[3,4],[4,5]])

data=np.array(list2D)
print(data)
print(data.shape)
print(data.ndim)

[[1 2]
 [3 4]
 [4 5]]
(3, 2)
2


In [10]:
#Create Numpy array

#---------------------
#zeros function
arr=np.zeros((2,3))
print(arr)

#--------------------
#ones function()
arr=np.ones((2,3))
print(arr)

#--------------------
#full function() --> Tao phan tu fill_value

arr=np.full((2,3),2,dtype="float")
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]]


In [15]:
# arange() function
arr=np.arange(5)
print(arr)

arr=np.arange(0,5,2)
print(arr)

#Tao 1 numpy array voi duong cheo la so 1 so 0 duoc dien vao o con lai
arr=np.eye(3)
print(arr)

#random() function
arr=np.random.random((2,3))
print(arr)

[0 1 2 3 4]
[0 2 4]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.93476684 0.18949464 0.62471729]
 [0.83391586 0.58427847 0.25262551]]


In [16]:
#SOME IMPORTANT FUNCTION

from unittest import result


data=np.array([1,2,3,4,5])
print("data: ",data)

#element < 3 se gan = 3
#element > 6 se gan bang 6
result = np.clip(data, a_min=3,a_max=6)
print("result: ",result)



data:  [1 2 3 4 5]
result:  [3 3 3 4 5]


In [20]:
# function hstack() - ket hop array theo chieu ngang

arr=np.array([1,2,3])
print("arr: ",arr)

arr1=np.array([4,5,6])
print("arr1: ",arr1)

res=np.hstack((arr,arr1))
print("res horizontal: ",res)
res1=np.vstack((arr,arr1))
print("res vertical:\n ",res1)

arr:  [1 2 3]
arr1:  [4 5 6]
res horizontal:  [1 2 3 4 5 6]
res vertical:
  [[1 2 3]
 [4 5 6]]


In [29]:
#function concatenate()
arr=np.array([[1,2,3]])
print("arr: ",arr)
print("arr shape: ",arr.shape)

arr1=np.array([[4,5,6]])
print("arr1: ",arr1)
print("arr1.shape: ",arr1.shape)

#Noi 2 array theo chieu ngang 
result=np.concatenate((arr1,arr),axis=0)
print("result: ",result)

arr:  [[1 2 3]]
arr shape:  (1, 3)
arr1:  [[4 5 6]]
arr1.shape:  (1, 3)
result:  [[4 5 6]
 [1 2 3]]


In [31]:
arr=np.array([1,2,3,4,5])
print("arr.shape: ",arr.shape)

#1D array -> 2D array
arr2d=arr[:,np.newaxis]
print("2D array ",arr2d)

arr2r=arr[np.newaxis,:]
print(arr2r)
#------------------TRANG 33-------------------------

arr.shape:  (5,)
2D array  [[1]
 [2]
 [3]
 [4]
 [5]]
[[1 2 3 4 5]]
